//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text;
using System.Collections.Generic;
using System;

namespace SystemEx.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Active.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ArrowHovered {
            get {
                object obj = ResourceManager.GetObject("ArrowHovered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowNormal {
            get {
                object obj = ResourceManager.GetObject("ArrowNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calculator {
            get {
                object obj = ResourceManager.GetObject("calculator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChevronLess {
            get {
                object obj = ResourceManager.GetObject("ChevronLess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChevronLessHovered {
            get {
                object obj = ResourceManager.GetObject("ChevronLessHovered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChevronLessPressed {
            get {
                object obj = ResourceManager.GetObject("ChevronLessPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChevronMore {
            get {
                object obj = ResourceManager.GetObject("ChevronMore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChevronMoreHovered {
            get {
                object obj = ResourceManager.GetObject("ChevronMoreHovered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChevronMorePressed {
            get {
                object obj = ResourceManager.GetObject("ChevronMorePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropDown2003 {
            get {
                object obj = ResourceManager.GetObject("DropDown2003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropDown2007 {
            get {
                object obj = ResourceManager.GetObject("DropDown2007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Grip2003 {
            get {
                object obj = ResourceManager.GetObject("Grip2003", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Grip2007 {
            get {
                object obj = ResourceManager.GetObject("Grip2007", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MessageBoxIconError {
            get {
                object obj = ResourceManager.GetObject("MessageBoxIconError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MessageBoxIconInformation {
            get {
                object obj = ResourceManager.GetObject("MessageBoxIconInformation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MessageBoxIconQuestion {
            get {
                object obj = ResourceManager.GetObject("MessageBoxIconQuestion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MessageBoxIconStop {
            get {
                object obj = ResourceManager.GetObject("MessageBoxIconStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MessageBoxIconWarning {
            get {
                object obj = ResourceManager.GetObject("MessageBoxIconWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_close {
            get {
                object obj = ResourceManager.GetObject("navigate_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigation_left_disabled {
            get {
                object obj = ResourceManager.GetObject("navigation_left_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigation_left_enabled {
            get {
                object obj = ResourceManager.GetObject("navigation_left_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigation_left_pressed {
            get {
                object obj = ResourceManager.GetObject("navigation_left_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigation_left_selected {
            get {
                object obj = ResourceManager.GetObject("navigation_left_selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigation_right_disabled {
            get {
                object obj = ResourceManager.GetObject("navigation_right_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigation_right_enabled {
            get {
                object obj = ResourceManager.GetObject("navigation_right_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigation_right_pressed {
            get {
                object obj = ResourceManager.GetObject("navigation_right_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigation_right_selected {
            get {
                object obj = ResourceManager.GetObject("navigation_right_selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap processing_large {
            get {
                object obj = ResourceManager.GetObject("processing_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap processing_medium {
            get {
                object obj = ResourceManager.GetObject("processing_medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap processing_small {
            get {
                object obj = ResourceManager.GetObject("processing_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap themed_grip {
            get {
                object obj = ResourceManager.GetObject("themed_grip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
